<?php
 return array(
     'states' => array(
     'AL'=>'Alabama',
    'AK'=>'Alaska',
    'AZ'=>'Arizona',
    'AR'=>'Arkansas',
    'CA'=>'California',
    'CO'=>'Colorado',
    'CT'=>'Connecticut',
    'DE'=>'Delaware',
    'DC'=>'District of Columbia',
    'FL'=>'Florida',
    'GA'=>'Georgia',
    'HI'=>'Hawaii',
    'ID'=>'Idaho',
    'IL'=>'Illinois',
    'IN'=>'Indiana',
    'IA'=>'Iowa',
    'KS'=>'Kansas',
    'KY'=>'Kentucky',
    'LA'=>'Louisiana',
    'ME'=>'Maine',
    'MD'=>'Maryland',
    'MA'=>'Massachusetts',
    'MI'=>'Michigan',
    'MN'=>'Minnesota',
    'MS'=>'Mississippi',
    'MO'=>'Missouri',
    'MT'=>'Montana',
    'NE'=>'Nebraska',
    'NV'=>'Nevada',
    'NH'=>'New Hampshire',
    'NJ'=>'New Jersey',
    'NM'=>'New Mexico',
    'NY'=>'New York',
    'NC'=>'North Carolina',
    'ND'=>'North Dakota',
    'OH'=>'Ohio',
    'OK'=>'Oklahoma',
    'OR'=>'Oregon',
    'PA'=>'Pennsylvania',
    'RI'=>'Rhode Island',
    'SC'=>'South Carolina',
    'SD'=>'South Dakota',
    'TN'=>'Tennessee',
    'TX'=>'Texas',
    'UT'=>'Utah',
    'VT'=>'Vermont',
    'VA'=>'Virginia',
    'WA'=>'Washington',
    'WV'=>'West Virginia',
    'WI'=>'Wisconsin',
    'WY'=>'Wyoming',
    ),
     
   'user_roles'=> array(
       User::ROLE_STUDENT => 'Student',
       User::ROLE_WORK_STUDY => 'Work Study',
       User::ROLE_ADMINISTRATOR => 'Administrator',
       User::ROLE_FACULTY => 'Faculty',
       User::ROLE_SYSTEM_ADMIN => 'System Admin',
       User::ROLE_CASHIER => 'Cashier'
     ),

   'user_statuses'=> array(
       User::STATUS_UNLOCKED => 'Unlocked',
       User::STATUS_LOCKED => 'Locked',
       User::STATUS_DEACTIVATED => 'Deactivated'
     ),

     'pp' => array(
         100 => 100,
         200 => 200,
         300 => 300,
         20000 => 'All',
     ),
     'disposal' => array(
         'Donation' => 'Donation',
         'Sold' => 'Sold',
         'Trade' => 'Trade',
         'E-waste' => 'E-waste',
     ),
     'connect_types' => array(
         'none' => 'None',
         'both' => 'Both',
         'wired' => 'Wired',
         'wireless' => 'Wireless',
     ),
 );